version: "3.1"

services:
  app:
    image: ghcr.io/102ch/thuuwa-tuuchi-bot:latest
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
